### ISSUE TITLE
newbie :) swift implementation problem

### ISSUE THREAD

**Issue by Mwiti** [maxep/MXParallaxBackground#1]
I'm getting as far as importing the headers in the bridging header. Need to know how to create the MXParallaxBackground variable... `let parallaxBG = MXParallaxBackground()` isn't working... Probably coz its not the way to do it... you tell me. :)  thanks.

**Comment by maxep** [comment]
Hi @Mwiti 
Did you import the framework ? you can check the swift example.

**Comment by Mwiti** [comment]
i had. turns out i had to build first after importing the framework before adding any code. hmmm.. thanks though :)
